### ISSUE TITLE
ebakus blockchain

### ISSUE THREAD

**Issue by abdulzabbar** [ebakus/indy-leaderboard#2]
The project is very promising.interesting and necessary for society. I want to be part of this event. I would like more people to know and join him.More on the website: www.ebakus.com  #blockchain #ethereum #ico #cryptocurrency#ebakus #ebakusnetwork @ebakusnetwork #EBK $EBK #gamingcommunity #Gamingblockchain #ICO

**Comment by dzmytry** [comment]
As for Ebakus, it specifications many times higher than all of the above features as Ethereum and EOS. The only thing that unites them is * DPOS * consensus and adapted smart contracts that can easily interact with the Ethereum blockchain and all DAPPsdeveloped on its basis. At the same time, the bandwidth of Ebakus is about 23 thousand transactions per second, where the minimum delay time is only 1 second. Moreover, within the framework of this blockchain, absolutely every transaction will be carried out without a token, which naturally reduces the cost of the transaction to the usual confirmation of work. This advantage allows to achieve maximum acceptance of the developed * DAPPs* to the masses, as well as to protect the bandwidth of the new system of interaction with the blockchain. However, in addition to all this Ebakus there is another distinctive feature that allows us to achieve a transparent basis for developers DAPPs and their user, and open access to the embedded wallet.
